const PREFIX_INCREMENT = 'newsApi/';

export const GET_ETH_LIST_SUCCESS = `${PREFIX_INCREMENT}REQUEST/GET_ETH_LIST_SUCCESS`;
export const GET_ETH_LIST_REQUEST = `${PREFIX_INCREMENT}REQUEST/GET_ETH_LIST_REQUEST`;
export const GET_ETH_LIST_FAILURE = `${PREFIX_INCREMENT}REQUEST/GET_ETH_LIST_FAILURE`;
